import { useState, useRef } from 'react'
import { FileText, Download, Type, Bold, Italic, AlignLeft, AlignCenter, AlignRight } from 'lucide-react'
import toast from 'react-hot-toast'
import { useAuth } from '../contexts/AuthContext'
import { useNavigate } from 'react-router-dom'

export default function TextToPdf() {
  const navigate = useNavigate()
  const { isPro, trackUsage, getRemainingUsage } = useAuth()
  const [text, setText] = useState('')
  const [title, setTitle] = useState('My Document')
  const [fontSize, setFontSize] = useState(14)
  const [alignment, setAlignment] = useState<'left' | 'center' | 'right'>('left')
  const [bold, setBold] = useState(false)
  const [italic, setItalic] = useState(false)
  const previewRef = useRef<HTMLDivElement>(null)

  const generatePdf = () => {
    if (!text.trim()) {
      toast.error('Please enter some text first')
      return
    }
    if (!title.trim()) {
      toast.error('Please enter a document title')
      return
    }

    if (!isPro) {
      const remaining = getRemainingUsage('pdfTools')
      if (remaining <= 0) {
        toast.error('Daily PDF credit limit reached! Upgrade to Pro.', { duration: 4000 })
        navigate('/upgrade')
        return
      }
    }

    trackUsage('pdfTools')

    const style = `
      <style>
        body { font-family: 'Georgia', serif; padding: 40px; font-size: ${fontSize}px; text-align: ${alignment}; line-height: 1.8; color: #1a1a1a; }
        h1 { font-size: 24px; margin-bottom: 20px; text-align: center; color: #000; border-bottom: 2px solid #eee; padding-bottom: 12px; ${bold ? 'font-weight: bold;' : ''} }
        p { white-space: pre-wrap; font-weight: ${bold ? 'bold' : 'normal'}; font-style: ${italic ? 'italic' : 'normal'}; }
        .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #eee; font-size: 11px; color: #999; text-align: center; }
      </style>
    `

    const html = `
      <html>${style}<body>
        <h1>${title}</h1>
        <p>${text.replace(/\n/g, '<br>')}</p>
        <div class="footer">Generated by Ekam Multi-Purpose Hub</div>
      </body></html>
    `

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const iframe = document.createElement('iframe')
    iframe.style.display = 'none'
    document.body.appendChild(iframe)

    if (iframe.contentWindow) {
      iframe.contentWindow.document.open()
      iframe.contentWindow.document.write(html)
      iframe.contentWindow.document.close()

      setTimeout(() => {
        try {
          iframe.contentWindow?.print()
        } catch {
          window.open(url, '_blank')
        }
        setTimeout(() => {
          document.body.removeChild(iframe)
          URL.revokeObjectURL(url)
        }, 1000)
      }, 500)
    }

    toast.success('PDF preview opened in print dialog')
  }

  const charCount = text.length
  const wordCount = text.trim() ? text.trim().split(/\s+/).length : 0
  const lineCount = text ? text.split('\n').length : 0

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
          <FileText size={24} className="text-primary-500" /> Text to PDF
        </h1>
        <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>
          Write or paste text and generate a styled PDF document. Uses browser print-to-PDF.
        </p>
      </div>

      {/* Text Input */}
      <div className="card space-y-3">
        <div>
          <label className="label">Document Title</label>
          <input
            type="text"
            value={title}
            onChange={e => setTitle(e.target.value)}
            placeholder="My Document"
            className="input"
          />
        </div>

        {/* Toolbar */}
        <div className="flex flex-wrap items-center gap-2 p-2 rounded-xl" style={{ backgroundColor: 'var(--bg-secondary)' }}>
          <button
            onClick={() => setBold(!bold)}
            className={`p-2 rounded-lg transition-colors ${bold ? 'bg-primary-500 text-white' : 'hover:bg-gray-200 dark:hover:bg-gray-700'}`}
            style={{ color: bold ? 'white' : 'var(--text-secondary)' }}
            title="Bold"
          >
            <Bold size={16} />
          </button>
          <button
            onClick={() => setItalic(!italic)}
            className={`p-2 rounded-lg transition-colors ${italic ? 'bg-primary-500 text-white' : 'hover:bg-gray-200 dark:hover:bg-gray-700'}`}
            style={{ color: italic ? 'white' : 'var(--text-secondary)' }}
            title="Italic"
          >
            <Italic size={16} />
          </button>
          <div className="w-px h-6" style={{ backgroundColor: 'var(--border)' }} />
          {(['left', 'center', 'right'] as const).map(align => (
            <button
              key={align}
              onClick={() => setAlignment(align)}
              className={`p-2 rounded-lg transition-colors ${alignment === align ? 'bg-primary-500 text-white' : 'hover:bg-gray-200 dark:hover:bg-gray-700'}`}
              style={{ color: alignment === align ? 'white' : 'var(--text-secondary)' }}
              title={`Align ${align}`}
            >
              {align === 'left' ? <AlignLeft size={16} /> : align === 'center' ? <AlignCenter size={16} /> : <AlignRight size={16} />}
            </button>
          ))}
          <div className="w-px h-6" style={{ backgroundColor: 'var(--border)' }} />
          <div className="flex items-center gap-2 text-sm">
            <Type size={14} style={{ color: 'var(--text-muted)' }} />
            <input
              type="range"
              min="10"
              max="28"
              value={fontSize}
              onChange={e => setFontSize(Number(e.target.value))}
              className="w-20"
            />
            <span style={{ color: 'var(--text-secondary)' }}>{fontSize}px</span>
          </div>
        </div>

        <div>
          <label className="label">Content</label>
          <textarea
            value={text}
            onChange={e => setText(e.target.value)}
            placeholder="Type or paste your text here..."
            className="input min-h-[250px] resize-y"
            rows={10}
          />
        </div>

        {/* Stats */}
        <div className="flex flex-wrap gap-4 text-xs" style={{ color: 'var(--text-muted)' }}>
          <span>{charCount} characters</span>
          <span>{wordCount} words</span>
          <span>{lineCount} lines</span>
        </div>

        <button onClick={generatePdf} disabled={!text.trim()} className="btn-primary w-full">
          <Download size={16} /> Generate & Download PDF
        </button>
      </div>

      {/* Preview */}
      {text.trim() && (
        <div className="card">
          <h3 className="font-semibold mb-3 text-sm" style={{ color: 'var(--text-primary)' }}>Preview</h3>
          <div
            ref={previewRef}
            className="rounded-xl border p-6 bg-white text-black"
            style={{ borderColor: 'var(--border)', fontSize: `${fontSize}px`, textAlign: alignment, fontWeight: bold ? 'bold' : 'normal', fontStyle: italic ? 'italic' : 'normal' }}
          >
            {title && <h2 className="text-xl font-bold mb-4 text-center border-b pb-2" style={{ borderColor: '#eee' }}>{title}</h2>}
            <p style={{ whiteSpace: 'pre-wrap' }}>{text}</p>
          </div>
        </div>
      )}
    </div>
  )
}
